### ISSUE TITLE
not able to login to Archlinux desktop environment after updating stardde 

### ISSUE THREAD

**Issue by taolin96** [linuxdeepin/startdde#9]
I am running Arch Linux with Deepin desktop environment and latest kernel 4.15.15-1-ARCH. after update startdde from 3.1.26-1 to 3.1.27-1, i am no longer able to login to the desktop environment. the xsession kept crashing, the following are the xsession-error log:

(process:874): GLib-GIO-ERROR **: 20:26:06.089: Settings schema 'com.deepin.dde.startdde' does not contain a key named 'iowait-enabled'
SIGTRAP: trace trap
PC=0x7fdc1d414ed2 m=0 sigcode=128

goroutine 0 [idle]:
runtime: unknown pc 0x7fdc1d414ed2
stack: frame={sp:0x7ffec56caf60, fp:0x0} stack=[0x7ffec4ecc320,0x7ffec56cb350)
00007ffec56cae60:  0000000000000058  9fb0a6fd337d5f00 
00007ffec56cae70:  0000000000000001  00007fdc1beca4e0 
00007ffec56cae80:  00005555e271d8f0  0000000000000004 
00007ffec56cae90:  0000000000000004  00007fdc1d417790 
00007ffec56caea0:  0000000000000000  00007fdc1d417729 
00007ffec56caeb0:  00005555e270d224  0000000000000004 
00007ffec56caec0:  00007ffec56caf70  0000000000000004 
00007ffec56caed0:  0000000000000000  0000000000000004 
00007ffec56caee0:  00005555e2710290  0000000000000004 
00007ffec56caef0:  00007ffec56caf70  00007fdc1d455f19 
00007ffec56caf00:  0000000000000000  0000000000000004 
00007ffec56caf10:  00007ffec56caf70  0000000000000004 
00007ffec56caf20:  0000000000000000  00007fdc1d415ac1 
00007ffec56caf30:  0000000000000000  0000000000000000 
00007ffec56caf40:  0000000000000004  0000000000000004 
00007ffec56caf50:  0000000000000004  00007fdc1d414ec9 
00007ffec56caf60: <0000000000000000  00007fdc1d415f7d 
00007ffec56caf70:  00007fdc1d462e05  00007fdc1d4b85c0 
00007ffec56caf80:  ffffffffffffffff  00007fdc1d462d48 
00007ffec56caf90:  00005555e270d1c0  ffffffffffffffff 
00007ffec56cafa0:  00007fdc1d462d5b  00007fdc1d462c35 
00007ffec56cafb0:  ffffffffffffffff  00007fdc1d462db5 
00007ffec56cafc0:  00007fdc1da4b758  ffffffffffffffff 
00007ffec56cafd0:  00005555e270d1c0  9fb0a6fd337d5f00 
00007ffec56cafe0:  0000000000000004  00007fdc1d41621f 
00007ffec56caff0:  00007fdc1da4b758  00005555e270d1c0 
00007ffec56cb000:  0000000100296928  00007fdc1d415ed0 
00007ffec56cb010:  0000000000000000  00007fdc1da4b758 
00007ffec56cb020:  00005555e2700064  0000000000000041 
00007ffec56cb030:  6b7365642e656d6f  616665642e706f74 
00007ffec56cb040:  6c7070612d746c75  736e6f6974616369 
00007ffec56cb050:  2e65636966666f2e  7261646e656c6163 
runtime: unknown pc 0x7fdc1d414ed2
stack: frame={sp:0x7ffec56caf60, fp:0x0} stack=[0x7ffec4ecc320,0x7ffec56cb350)
00007ffec56cae60:  0000000000000058  9fb0a6fd337d5f00 
00007ffec56cae70:  0000000000000001  00007fdc1beca4e0 
00007ffec56cae80:  00005555e271d8f0  0000000000000004 
00007ffec56cae90:  0000000000000004  00007fdc1d417790 
00007ffec56caea0:  0000000000000000  00007fdc1d417729 
00007ffec56caeb0:  00005555e270d224  0000000000000004 
00007ffec56caec0:  00007ffec56caf70  0000000000000004 
00007ffec56caed0:  0000000000000000  0000000000000004 
00007ffec56caee0:  00005555e2710290  0000000000000004 
00007ffec56caef0:  00007ffec56caf70  00007fdc1d455f19 
00007ffec56caf00:  0000000000000000  0000000000000004 
00007ffec56caf10:  00007ffec56caf70  0000000000000004 
00007ffec56caf20:  0000000000000000  00007fdc1d415ac1 
00007ffec56caf30:  0000000000000000  0000000000000000 
00007ffec56caf40:  0000000000000004  0000000000000004 
00007ffec56caf50:  0000000000000004  00007fdc1d414ec9 
00007ffec56caf60: <0000000000000000  00007fdc1d415f7d 
00007ffec56caf70:  00007fdc1d462e05  00007fdc1d4b85c0 
00007ffec56caf80:  ffffffffffffffff  00007fdc1d462d48 
00007ffec56caf90:  00005555e270d1c0  ffffffffffffffff 
00007ffec56cafa0:  00007fdc1d462d5b  00007fdc1d462c35 
00007ffec56cafb0:  ffffffffffffffff  00007fdc1d462db5 
00007ffec56cafc0:  00007fdc1da4b758  ffffffffffffffff 
00007ffec56cafd0:  00005555e270d1c0  9fb0a6fd337d5f00 
00007ffec56cafe0:  0000000000000004  00007fdc1d41621f 
00007ffec56caff0:  00007fdc1da4b758  00005555e270d1c0 
00007ffec56cb000:  0000000100296928  00007fdc1d415ed0 
00007ffec56cb010:  0000000000000000  00007fdc1da4b758 
00007ffec56cb020:  00005555e2700064  0000000000000041 
00007ffec56cb030:  6b7365642e656d6f  616665642e706f74 
00007ffec56cb040:  6c7070612d746c75  736e6f6974616369 
00007ffec56cb050:  2e65636966666f2e  7261646e656c6163 

goroutine 1 [syscall]:
runtime.cgocall(0x5555e1649e20, 0xc420065df8, 0x5555e2711ab0)
	/usr/lib/go/src/runtime/cgocall.go:128 +0x66 fp=0xc420065dc8 sp=0xc420065d90 pc=0x5555e12de6e6
gir/gio-2%2e0._Cfunc_g_settings_get_boolean(0x5555e26e3570, 0x5555e2711ab0, 0x0)
	_cgo_gotypes.go:8186 +0x4f fp=0xc420065df8 sp=0xc420065dc8 pc=0x5555e14d4fcf
gir/gio-2%2e0.(*Settings).GetBoolean.func2(0x5555e26e3570, 0x5555e2711ab0, 0x5555e2711ab0)
	/usr/share/gocode/src/gir/gio-2.0/gio.go:10188 +0x62 fp=0xc420065e30 sp=0xc420065df8 pc=0x5555e14da8d2
gir/gio-2%2e0.(*Settings).GetBoolean(0xc420154060, 0x5555e1663b98, 0xe, 0x0)
	/usr/share/gocode/src/gir/gio-2.0/gio.go:10188 +0x94 fp=0xc420065e68 sp=0xc420065e30 pc=0x5555e14d7e24
main.getGSettingsConfig(0x5555e1666a9d)
	/build/startdde/src/startdde-3.1.27/utils.go:247 +0x111 fp=0xc420065ec8 sp=0xc420065e68 pc=0x5555e163ee51
main.main()
	/build/startdde/src/startdde-3.1.27/main.go:66 +0x36 fp=0xc420065f88 sp=0xc420065ec8 pc=0x5555e163fc66
runtime.main()
	/usr/lib/go/src/runtime/proc.go:198 +0x21a fp=0xc420065fe0 sp=0xc420065f88 pc=0x5555e130869a
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420065fe8 sp=0xc420065fe0 pc=0x5555e1332ae1

goroutine 5 [IO wait]:
internal/poll.runtime_pollWait(0x7fdc1fd5ce30, 0x72, 0xc420014c10)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x59
internal/poll.(*pollDesc).wait(0xc4200e8798, 0x72, 0xc42013f300, 0x1000, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9d
internal/poll.(*pollDesc).waitRead(0xc4200e8798, 0xc420014c00, 0x10, 0x10)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f
internal/poll.(*FD).ReadMsg(0xc4200e8780, 0xc420014c10, 0x10, 0x10, 0xc42013f320, 0x1000, 0x1000, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/internal/poll/fd_unix.go:231 +0x1f3
net.(*netFD).readMsg(0xc4200e8780, 0xc420014c10, 0x10, 0x10, 0xc42013f320, 0x1000, 0x1000, 0x5555e1951640, 0xc420011ab0, 0xc420014b46, ...)
	/usr/lib/go/src/net/fd_unix.go:214 +0x92
net.(*UnixConn).readMsg(0xc42000e540, 0xc420014c10, 0x10, 0x10, 0xc42013f320, 0x1000, 0x1000, 0xc420014b46, 0x5555e19ece00, 0xc420014a7c, ...)
	/usr/lib/go/src/net/unixsock_posix.go:115 +0x93
net.(*UnixConn).ReadMsgUnix(0xc42000e540, 0xc420014c10, 0x10, 0x10, 0xc42013f320, 0x1000, 0x1000, 0xc4200d10a0, 0x7, 0xc420014b4c, ...)
	/usr/lib/go/src/net/unixsock.go:137 +0xac
pkg.deepin.io/lib/dbus.(*oobReader).Read(0xc42013f300, 0xc420014c10, 0x10, 0x10, 0x1020, 0xc42013f300, 0x0)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/transport_unix.go:38 +0x91
io.ReadAtLeast(0x5555e19e9500, 0xc42013f300, 0xc420014c10, 0x10, 0x10, 0x10, 0x5555e1997900, 0x1, 0xc42013f300)
	/usr/lib/go/src/io/io.go:309 +0x88
io.ReadFull(0x5555e19e9500, 0xc42013f300, 0xc420014c10, 0x10, 0x10, 0xc420061cf8, 0x5555e1320571, 0x30)
	/usr/lib/go/src/io/io.go:327 +0x5a
pkg.deepin.io/lib/dbus.(*unixTransport).ReadMessage(0xc420011560, 0xc420098960, 0x14, 0x5555e165c8ac)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/transport_unix.go:98 +0x115
pkg.deepin.io/lib/dbus.(*Conn).inWorker(0xc4200b4c60)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/conn.go:265 +0x4d
created by pkg.deepin.io/lib/dbus.(*Conn).Auth
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/auth.go:139 +0x6c5

goroutine 6 [chan receive]:
pkg.deepin.io/lib/dbus.(*Conn).outWorker(0xc4200b4c60)
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/conn.go:387 +0x65
created by pkg.deepin.io/lib/dbus.(*Conn).Auth
	/usr/share/gocode/src/pkg.deepin.io/lib/dbus/auth.go:140 +0x6ea

rax    0x0
rbx    0x1
rcx    0x7fdc1bec9b00
rdx    0x1
rdi    0x1
rsi    0x0
rbp    0x4
rsp    0x7ffec56caf60
r8     0x7
r9     0x7fdc1fdb8980
r10    0x7fdc1bc8c640
r11    0x0
r12    0x4
r13    0x4
r14    0x6
r15    0x2
rip    0x7fdc1d414ed2
rflags 0x202
cs     0x33
fs     0x0
gs     0x0

**Comment by Swizz** [comment]
Looks like they released `startdde` but not the Deepin desktop schemas package with the changes that make use stuck at login screen :/

**Comment by Swizz** [comment]
@taolin96 If you are still stuck at the login screen you should downgrade the `startdde` package : 
```sh
pacman -U /var/cache/pacman/pkg/startdde-3.1.26-1-x86_64.pkg.tar.xz
```

**Comment by felixonmars** [comment]
Please try again with deepin-desktop-schemas 3.2.9.20180409-1

**Comment by Swizz** [comment]
`deepin-desktop-schemas 3.2.9.20180409-1` fix the issue
